version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "5030:5030"
    env_file:
      - ./backend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 5030 --timeout-keep-alive 75

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5020:80"
    restart: always

volumes: {}
