"""add return order and return items

Revision ID: 27a4345486a3
Revises: 911a6de2bc20
Create Date: 2026-07-02 23:12:21.023432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '27a4345486a3'
down_revision: Union[str, None] = '911a6de2bc20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('return_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomor_return', sa.String(length=50), nullable=False),
    sa.Column('pengiriman_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'REVIEWED', name='statusreturnorder'), nullable=False),
    sa.Column('catatan_driver', sa.String(length=1000), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('catatan_reviewer', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pengiriman_id'], ['pengiriman.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_orders_id'), 'return_orders', ['id'], unique=False)
    op.create_index(op.f('ix_return_orders_nomor_return'), 'return_orders', ['nomor_return'], unique=True)
    op.create_table('return_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_order_id', sa.Integer(), nullable=False),
    sa.Column('production_unit_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('mo_id', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.Enum('SISA', 'RUSAK', name='kategorireturn'), nullable=False),
    sa.Column('kondisi_konfirmasi', sa.Enum('PENDING', 'BAIK', 'RUSAK_KONFIRMASI', name='kondisikonfirmasi'), nullable=False),
    sa.Column('catatan_driver', sa.String(length=500), nullable=True),
    sa.Column('catatan_reviewer', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mo_id'], ['manufacturing_orders.id'], ),
    sa.ForeignKeyConstraint(['production_unit_id'], ['production_units.id'], ),
    sa.ForeignKeyConstraint(['return_order_id'], ['return_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_items_barcode'), 'return_items', ['barcode'], unique=False)
    op.create_index(op.f('ix_return_items_id'), 'return_items', ['id'], unique=False)
    op.add_column('production_units', sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_units', 'returned_at')
    op.drop_index(op.f('ix_return_items_id'), table_name='return_items')
    op.drop_index(op.f('ix_return_items_barcode'), table_name='return_items')
    op.drop_table('return_items')
    op.drop_index(op.f('ix_return_orders_nomor_return'), table_name='return_orders')
    op.drop_index(op.f('ix_return_orders_id'), table_name='return_orders')
    op.drop_table('return_orders')
    # ### end Alembic commands ###
