"""add harga_modal to production_unit

Revision ID: 794712529f56
Revises: 27a4345486a3
Create Date: 2026-07-02 23:18:16.599317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '794712529f56'
down_revision: Union[str, None] = '27a4345486a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_units', sa.Column('harga_modal', sa.Numeric(precision=12, scale=2), nullable=True, comment='Harga modal per unit, diisi tim produksi. Dipakai untuk hitung kerugian riil.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_units', 'harga_modal')
    # ### end Alembic commands ###
