"""add manufacturing order

Revision ID: 8cbe819df1ec
Revises: 92c84bea15aa
Create Date: 2026-07-02 22:56:36.784068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8cbe819df1ec'
down_revision: Union[str, None] = '92c84bea15aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturing_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomor_mo', sa.String(length=50), nullable=False),
    sa.Column('nama_produk', sa.String(length=255), nullable=False),
    sa.Column('target_qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('satuan', sa.String(length=50), nullable=False),
    sa.Column('tanggal_rencana', sa.Date(), nullable=False),
    sa.Column('tanggal_mulai', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tanggal_selesai', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'IN_PROGRESS', 'DONE', 'CANCELLED', name='statusmo'), nullable=False),
    sa.Column('catatan', sa.String(length=1000), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manufacturing_orders_id'), 'manufacturing_orders', ['id'], unique=False)
    op.create_index(op.f('ix_manufacturing_orders_nomor_mo'), 'manufacturing_orders', ['nomor_mo'], unique=True)
    op.create_table('mo_bahan_baku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mo_id', sa.Integer(), nullable=False),
    sa.Column('bahan_baku_id', sa.Integer(), nullable=False),
    sa.Column('qty_rencana', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('qty_aktual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('satuan', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['bahan_baku_id'], ['bahan_baku.id'], ),
    sa.ForeignKeyConstraint(['mo_id'], ['manufacturing_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mo_bahan_baku_id'), 'mo_bahan_baku', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mo_bahan_baku_id'), table_name='mo_bahan_baku')
    op.drop_table('mo_bahan_baku')
    op.drop_index(op.f('ix_manufacturing_orders_nomor_mo'), table_name='manufacturing_orders')
    op.drop_index(op.f('ix_manufacturing_orders_id'), table_name='manufacturing_orders')
    op.drop_table('manufacturing_orders')
    # ### end Alembic commands ###
