"""add expiry_date to production_unit

Revision ID: 911a6de2bc20
Revises: f9e0d9db79e0
Create Date: 2026-07-02 23:03:37.726560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '911a6de2bc20'
down_revision: Union[str, None] = 'f9e0d9db79e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_units', sa.Column('expiry_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_units', 'expiry_date')
    # ### end Alembic commands ###
