"""initial

Revision ID: 92c84bea15aa
Revises: 
Create Date: 2026-07-02 22:48:09.068578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '92c84bea15aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bahan_baku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('satuan', sa.String(length=50), nullable=False),
    sa.Column('stok_minimum', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deskripsi', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bahan_baku_id'), 'bahan_baku', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PRODUKSI', 'INVENTORI', 'DRIVER', 'SHAREHOLDER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('pengiriman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('tujuan', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DALAM_PERJALANAN', 'TERKIRIM', 'GAGAL', name='statuspengiriman'), nullable=False),
    sa.Column('catatan', sa.String(length=1000), nullable=True),
    sa.Column('tanggal_kirim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tanggal_tiba', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pengiriman_id'), 'pengiriman', ['id'], unique=False)
    op.create_table('produksi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_batch', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PROSES', 'SELESAI', 'BATAL', name='statusproduksi'), nullable=False),
    sa.Column('jumlah_output', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('satuan_output', sa.String(length=50), nullable=False),
    sa.Column('catatan', sa.String(length=1000), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produksi_id'), 'produksi', ['id'], unique=False)
    op.create_table('stok',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bahan_baku_id', sa.Integer(), nullable=False),
    sa.Column('tipe', sa.Enum('MASUK', 'KELUAR', name='tipetransaksistok'), nullable=False),
    sa.Column('jumlah', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('keterangan', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bahan_baku_id'], ['bahan_baku.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stok_id'), 'stok', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stok_id'), table_name='stok')
    op.drop_table('stok')
    op.drop_index(op.f('ix_produksi_id'), table_name='produksi')
    op.drop_table('produksi')
    op.drop_index(op.f('ix_pengiriman_id'), table_name='pengiriman')
    op.drop_table('pengiriman')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_bahan_baku_id'), table_name='bahan_baku')
    op.drop_table('bahan_baku')
    # ### end Alembic commands ###
