"""add production unit and penjualan

Revision ID: f9e0d9db79e0
Revises: 8cbe819df1ec
Create Date: 2026-07-02 23:02:04.328092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f9e0d9db79e0'
down_revision: Union[str, None] = '8cbe819df1ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('mo_id', sa.Integer(), nullable=False),
    sa.Column('nama_produk', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('READY', 'DISPATCHED', 'DELIVERED', 'SOLD', 'VOID', name='statusunit'), nullable=False),
    sa.Column('pengiriman_id', sa.Integer(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mo_id'], ['manufacturing_orders.id'], ),
    sa.ForeignKeyConstraint(['pengiriman_id'], ['pengiriman.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_units_barcode'), 'production_units', ['barcode'], unique=True)
    op.create_index(op.f('ix_production_units_id'), 'production_units', ['id'], unique=False)
    op.create_table('penjualan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_unit_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('nama_produk', sa.String(length=255), nullable=False),
    sa.Column('harga', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('catatan', sa.String(length=500), nullable=True),
    sa.Column('kasir_id', sa.Integer(), nullable=False),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kasir_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['production_unit_id'], ['production_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_unit_id')
    )
    op.create_index(op.f('ix_penjualan_barcode'), 'penjualan', ['barcode'], unique=False)
    op.create_index(op.f('ix_penjualan_id'), 'penjualan', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_penjualan_id'), table_name='penjualan')
    op.drop_index(op.f('ix_penjualan_barcode'), table_name='penjualan')
    op.drop_table('penjualan')
    op.drop_index(op.f('ix_production_units_id'), table_name='production_units')
    op.drop_index(op.f('ix_production_units_barcode'), table_name='production_units')
    op.drop_table('production_units')
    # ### end Alembic commands ###
